/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cpu.scheduling.pkg2;

import javax.swing.JTextField;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel; 
import org.jfree.chart.JFreeChart; 
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.CategoryDataset; 
import org.jfree.data.category.DefaultCategoryDataset; 
import org.jfree.ui.ApplicationFrame; 
import org.jfree.ui.RefineryUtilities; 

/**
 *
 * @author Have_Fun
 */
public class ChoiceMethod extends javax.swing.JFrame {

    /**
     * Creates new form ChoiceMethod
     */
    float a,a1,a2,a3,a4,a5=0;
      public static dowork x;
    public ChoiceMethod(dowork x) {
        initComponents();
        this.x=x;
        new NumberofProcess(this, rootPaneCheckingEnabled,this.x);
    }
    class BarChart2 extends ApplicationFrame {
    public float s1=a ,s2=a1 ,s3=a3 ,s4=a2,s5=a4 ,s6=a5; 
  
     BarChart2(String title) {
        super(title);
    
     //      BarChart_AWT chart1 = new BarChart_AWT("", 
//         "");
//       chart1.ruv();
 BarChart2 chart = new BarChart2 ("Bar Chart", 
         "");
      chart.pack( );        
      RefineryUtilities.centerFrameOnScreen( chart );        
      chart.setVisible( true );
     }
   
    BarChart2( String applicationTitle , String chartTitle ) {
      super( applicationTitle );        
      JFreeChart barChart = ChartFactory.createBarChart(
         chartTitle,           
         "Category",            
         "Time",            
         createDataset(),          
         PlotOrientation.VERTICAL,           
         true, true, false);
         
      ChartPanel chartPanel = new ChartPanel( barChart );        
      chartPanel.setPreferredSize(new java.awt.Dimension( 560 , 367 ) );        
      setContentPane( chartPanel ); 
      
  
      
      
   }
   
   private CategoryDataset createDataset( ) {
      final String fcfs = "FCFS";        
      final String sjf = "SJF";        
      final String sjfp = "SJFP";
      final String sjfnp = "SJFNP";
      final String periority = "PRIORITY";
      final String roundRobin = "ROUND ROBIN";        
      final DefaultCategoryDataset dataset = 
      new DefaultCategoryDataset( );  

    dataset.addValue( s1 , fcfs , "TECNIQUE" );        
    dataset.addValue( s2 , sjf , "TECNIQUE" );        
    dataset.addValue( s3 , sjfp , "TECNIQUE" );        
    dataset.addValue( s4 , sjfnp , "TECNIQUE" );
    dataset.addValue( s5 , periority , "TECNIQUE" );
    dataset.addValue( s6 , roundRobin , "TECNIQUE" );

      return dataset; 
   }
   
   
   void ruv (){
       BarChart2 chart = new BarChart2 ("Car Usage Statistics", 
         "Which car do you like?");
      chart.pack( );        
      RefineryUtilities.centerFrameOnScreen( chart );        
      chart.setVisible( true ); 
   }
   
   
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                         dispose();
                    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        p1id = new javax.swing.JTextField();
        p2id = new javax.swing.JTextField();
        p3id = new javax.swing.JTextField();
        p4id = new javax.swing.JTextField();
        p5id = new javax.swing.JTextField();
        p6id = new javax.swing.JTextField();
        p7id = new javax.swing.JTextField();
        p8id = new javax.swing.JTextField();
        p9id = new javax.swing.JTextField();
        p10id = new javax.swing.JTextField();
        p1a = new javax.swing.JTextField();
        p2a = new javax.swing.JTextField();
        p3a = new javax.swing.JTextField();
        p4a = new javax.swing.JTextField();
        p5a = new javax.swing.JTextField();
        p6a = new javax.swing.JTextField();
        p7a = new javax.swing.JTextField();
        p8a = new javax.swing.JTextField();
        p9a = new javax.swing.JTextField();
        p10a = new javax.swing.JTextField();
        p2b = new javax.swing.JTextField();
        p3b = new javax.swing.JTextField();
        p4b = new javax.swing.JTextField();
        p5b = new javax.swing.JTextField();
        p6b = new javax.swing.JTextField();
        p7b = new javax.swing.JTextField();
        p8b = new javax.swing.JTextField();
        p9b = new javax.swing.JTextField();
        p10b = new javax.swing.JTextField();
        p1b = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        Qtime = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel1.setText("p2");

        jLabel2.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel2.setText("p1");

        jLabel3.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel3.setText("p4");

        jLabel4.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel4.setText("p3");

        jLabel5.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel5.setText("p7");

        jLabel6.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel6.setText("p8");

        jLabel7.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel7.setText("p6");

        jLabel8.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel8.setText("p5");

        jLabel9.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel9.setText("p10");

        jLabel10.setFont(new java.awt.Font("Elephant", 1, 18)); // NOI18N
        jLabel10.setText("p9");

        p1id.setBackground(new java.awt.Color(250, 250, 250));
        p1id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p2id.setBackground(new java.awt.Color(250, 250, 250));
        p2id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p3id.setBackground(new java.awt.Color(250, 250, 250));
        p3id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p4id.setBackground(new java.awt.Color(250, 250, 250));
        p4id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p5id.setBackground(new java.awt.Color(250, 250, 250));
        p5id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p6id.setBackground(new java.awt.Color(250, 250, 250));
        p6id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p7id.setBackground(new java.awt.Color(250, 250, 250));
        p7id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p8id.setBackground(new java.awt.Color(250, 250, 250));
        p8id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p9id.setBackground(new java.awt.Color(250, 250, 250));
        p9id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p10id.setBackground(new java.awt.Color(250, 250, 250));
        p10id.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p1a.setBackground(new java.awt.Color(250, 250, 250));
        p1a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p2a.setBackground(new java.awt.Color(250, 250, 250));
        p2a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p3a.setBackground(new java.awt.Color(250, 250, 250));
        p3a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p4a.setBackground(new java.awt.Color(250, 250, 250));
        p4a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p5a.setBackground(new java.awt.Color(250, 250, 250));
        p5a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p6a.setBackground(new java.awt.Color(250, 250, 250));
        p6a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p7a.setBackground(new java.awt.Color(250, 250, 250));
        p7a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p8a.setBackground(new java.awt.Color(250, 250, 250));
        p8a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p9a.setBackground(new java.awt.Color(250, 250, 250));
        p9a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p10a.setBackground(new java.awt.Color(250, 250, 250));
        p10a.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p2b.setBackground(new java.awt.Color(250, 250, 250));
        p2b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p3b.setBackground(new java.awt.Color(250, 250, 250));
        p3b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p4b.setBackground(new java.awt.Color(250, 250, 250));
        p4b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p5b.setBackground(new java.awt.Color(250, 250, 250));
        p5b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p6b.setBackground(new java.awt.Color(250, 250, 250));
        p6b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p7b.setBackground(new java.awt.Color(250, 250, 250));
        p7b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p8b.setBackground(new java.awt.Color(250, 250, 250));
        p8b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p9b.setBackground(new java.awt.Color(250, 250, 250));
        p9b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p10b.setBackground(new java.awt.Color(250, 250, 250));
        p10b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N

        p1b.setBackground(new java.awt.Color(250, 250, 250));
        p1b.setFont(new java.awt.Font("Engravers MT", 1, 14)); // NOI18N
        p1b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p1bActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p2b)
                    .addComponent(p3b)
                    .addComponent(p4b)
                    .addComponent(p5b)
                    .addComponent(p6b)
                    .addComponent(p7b)
                    .addComponent(p8b)
                    .addComponent(p9b)
                    .addComponent(p10b, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p1b))
                .addGap(95, 95, 95)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p1a)
                    .addComponent(p2a)
                    .addComponent(p3a)
                    .addComponent(p4a)
                    .addComponent(p5a)
                    .addComponent(p6a)
                    .addComponent(p7a)
                    .addComponent(p8a)
                    .addComponent(p9a)
                    .addComponent(p10a, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(p1id)
                    .addComponent(p2id)
                    .addComponent(p3id)
                    .addComponent(p4id)
                    .addComponent(p5id)
                    .addComponent(p6id)
                    .addComponent(p7id)
                    .addComponent(p8id)
                    .addComponent(p9id)
                    .addComponent(p10id, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p3id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p4id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p5id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p6id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p7id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p8id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p9id, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p10id, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(p1a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p2a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p3a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p4a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p5a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(p6a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(p7a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p8a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(p9a, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(p10a, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p1b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p2b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p3b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p4b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p5b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(p6b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p7b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p8b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p9b, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p10b, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );

        jButton1.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton1.setText("Compair");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel11.setText("Brust Time");

        jLabel22.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel22.setText("Arrival Time");

        jLabel23.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        jLabel23.setText("Periority");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel11)
                .addGap(74, 74, 74)
                .addComponent(jLabel22)
                .addGap(91, 91, 91)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)))
        );

        jButton6.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton6.setText("FcFs");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton7.setText("SJFNP");
        jButton7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton8.setText("SJF");
        jButton8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton9.setText("Priority");
        jButton9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton10.setText("SJFP");
        jButton10.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton11.setText("RR");
        jButton11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setFont(new java.awt.Font("Ebrima", 1, 12)); // NOI18N
        jButton12.setText("Get Data");
        jButton12.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        Qtime.setFont(new java.awt.Font("Goudy Old Style", 1, 14)); // NOI18N
        Qtime.setForeground(new java.awt.Color(255, 0, 0));

        jLabel24.setFont(new java.awt.Font("Gadugi", 1, 14)); // NOI18N
        jLabel24.setText("Quantum time");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Qtime))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel24)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Qtime)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         new BarChart2("style");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        x.Fcfs();
        new NumberofProcess(this, rootPaneCheckingEnabled, x).setVisible(true);
        a=x.Awt;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
             JTextField []Wtime=new JTextField[10];
       Wtime[0]=p1a;
       Wtime[1]=p2a;
       Wtime[2]=p3a;
       Wtime[3]=p4a;
       Wtime[4]=p5a;
       Wtime[5]=p6a;
       Wtime[6]=p7a;
       Wtime[7]=p8a;
       Wtime[8]=p9a;
       Wtime[9]=p10a;
        
       for(int i=0;i<10;i++){
        if(!Wtime[i].getText().isEmpty()){
            try {
            x.A[i+1]=Float.parseFloat(Wtime[i].getText());
               
               
                System.out.println(x.A[i]+" "+x.n);
            } catch (Exception e) {
                e.printStackTrace();
                
            }
            
        }else{
            System.out.println("Problem Arise "+x.n+" "+x.A[i]);
              
        }
       }
         if(Wtime[0].getText().isEmpty()){
            new error(this, rootPaneCheckingEnabled, "Arrival Time").setVisible(true);
        }
         x.SjfNp();
                 new NumberofProcess(this, rootPaneCheckingEnabled, x).setVisible(true);
                 
                 a2=x.Awt;
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    
        x.Sjf();
       new NumberofProcess(this, rootPaneCheckingEnabled, x).setVisible(true);
       a1=x.Awt;

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       JTextField []Pid=new JTextField[10];

       Pid[0]=p1id;
       Pid[1]=p2id;
       Pid[2]=p3id;
       Pid[3]=p4id;
       Pid[4]=p5id;
       Pid[5]=p6id;
       Pid[6]=p7id;
       Pid[7]=p8id;
       Pid[8]=p9id;
       Pid[9]=p10id;
        
       for(int i=0;i<10;i++){
        if(!Pid[i].getText().isEmpty()){
            try {
            x.P[i+1]=Integer.parseInt(Pid[i].getText());
               
               
                System.out.println(x.A[i]+" "+x.n);
            } catch (Exception e) {
                e.printStackTrace();
                
            }
            
        }else{
            System.out.println("Problem Arise "+x.n+" "+x.A[i]);
              
        }
       }
         if(Pid[0].getText().isEmpty()){
            new error(this, rootPaneCheckingEnabled, "Priority id").setVisible(true);
        }
         x.Priority();
         new NumberofProcess(this, rootPaneCheckingEnabled, x).setVisible(true);
         a4=x.Awt;
        
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
                  JTextField []Wtime=new JTextField[10];
       Wtime[0]=p1a;
       Wtime[1]=p2a;
       Wtime[2]=p3a;
       Wtime[3]=p4a;
       Wtime[4]=p5a;
       Wtime[5]=p6a;
       Wtime[6]=p7a;
       Wtime[7]=p8a;
       Wtime[8]=p9a;
       Wtime[9]=p10a;
        
       for(int i=0;i<10;i++){
        if(!Wtime[i].getText().isEmpty()){
            try {
            x.A[i+1]=Float.parseFloat(Wtime[i].getText());
               
               
                System.out.println(x.A[i]+" "+x.n);
            } catch (Exception e) {
                e.printStackTrace();
                
            }
            
        }else{
            System.out.println("Problem Arise "+x.n+" "+x.A[i]);
              
        }
       }
         if(Wtime[0].getText().isEmpty()){
            new error(this, rootPaneCheckingEnabled, "Arrival Time").setVisible(true);
        }
         x.sjfp2();
         new NumberofProcess(this, rootPaneCheckingEnabled, x).setVisible(true);
         a3=x.Awt;
        
        
        
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       
               if(x.Bu[1]==0){
            new error(this, rootPaneCheckingEnabled, "Check data").setVisible(true);
        }
               if(Qtime.getText().isEmpty()){
                               new error(this, rootPaneCheckingEnabled, "quantum time").setVisible(true);

               }else{
                   x.tq=Integer.parseInt(Qtime.getText());
                   x.RoundRobin();
                      new NumberofProcess(this, rootPaneCheckingEnabled, x).setVisible(true);

               }
        
        a5=x.Awt;
    }//GEN-LAST:event_jButton11ActionPerformed

    private void p1bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p1bActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p1bActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
       JTextField []brusttext=new JTextField[10];
       brusttext[0]=p1b;
       brusttext[1]=p2b;
       brusttext[2]=p3b;
       brusttext[3]=p4b;
       brusttext[4]=p5b;
       brusttext[5]=p6b;
       brusttext[6]=p7b;
       brusttext[7]=p8b;
       brusttext[8]=p9b;
       brusttext[9]=p10b;
     
       for(int i=0;i<10;i++){
        if(!brusttext[i].getText().isEmpty()){
            try {
            x.Bu[i+1]=Integer.parseInt(brusttext[i].getText());
                
                x.n++;
                System.out.println(x.Bu[i]+" "+x.n);
            } catch (Exception e) {
                e.printStackTrace();
                
            }
            
        }else{
            System.out.println("Problem Arise "+x.n);
              
        }
       }
         if(brusttext[0].getText().isEmpty()){
            new error(this, rootPaneCheckingEnabled, "Brust Process Time").setVisible(true);
        }
   
   
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChoiceMethod.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChoiceMethod(x).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Qtime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField p10a;
    private javax.swing.JTextField p10b;
    private javax.swing.JTextField p10id;
    private javax.swing.JTextField p1a;
    private javax.swing.JTextField p1b;
    private javax.swing.JTextField p1id;
    private javax.swing.JTextField p2a;
    private javax.swing.JTextField p2b;
    private javax.swing.JTextField p2id;
    private javax.swing.JTextField p3a;
    private javax.swing.JTextField p3b;
    private javax.swing.JTextField p3id;
    private javax.swing.JTextField p4a;
    private javax.swing.JTextField p4b;
    private javax.swing.JTextField p4id;
    private javax.swing.JTextField p5a;
    private javax.swing.JTextField p5b;
    private javax.swing.JTextField p5id;
    private javax.swing.JTextField p6a;
    private javax.swing.JTextField p6b;
    private javax.swing.JTextField p6id;
    private javax.swing.JTextField p7a;
    private javax.swing.JTextField p7b;
    private javax.swing.JTextField p7id;
    private javax.swing.JTextField p8a;
    private javax.swing.JTextField p8b;
    private javax.swing.JTextField p8id;
    private javax.swing.JTextField p9a;
    private javax.swing.JTextField p9b;
    private javax.swing.JTextField p9id;
    // End of variables declaration//GEN-END:variables
}
